### PR TITLE
ENH: community: add a pointer to 2024 minutes

### PR DESCRIPTION
**Pull request by SantiagoTorres**
We have since moved to hackmd, but we want people who check this repo to know that!

### CODE REVIEW

**Comment by adityasaky** [comment]
actually, I think we (I) have been slacking in moving things from the hackmd to the repository 😬

**Comment by SantiagoTorres** [comment]
I wonder if we need to, or just use the pointer

**Comment by 06kellyjac** [comment]
Maybe this is something we can discuss at the meeting this Friday?

**Comment by matglas** [comment]
I would say. Keep it simple and just merge it. It has been the go to for the whole year and its helpful for the community to find it.

**Comment by SantiagoTorres** [comment]
Thank you, @JustinCappos ! for the record, we discussed this in the itsc channel

**Pull request merged**
